[package]
name = "ws-p2p"
version = "0.1.0"
authors = ["Jonathan Almeida <hello@jonalmeida.com>"]

[dependencies]
ws = "0.4.*"
url = "*"
clap = "*"
env_logger = "*"
log = "*"
rustc-serialize = "*"
bincode = "*"
