[package]
name = "ws-p2p"
version = "0.1.0"
authors = ["Jonathan Almeida <hello@jonalmeida.com>"]

[dependencies]
ws = "0.4.*"
url = "0.5.*"
clap = "2.1.*"
env_logger = "0.3.*"
log = "0.3.*"
rustc-serialize = "0.3.*"
bincode = "0.4.*"
